name: Run tests
on: [push, pull_request]

jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False  # Always run all tests
      matrix:
        python: [3.7.10, 3.8.10, 3.9.9, 3.10.1]
        extras: ["test", "test,queable,sentry"]
        section: ["client", "api", "ingester"]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Test
        working-directory: ./${{ matrix.section }}
        run: |
          pip install -e .[${{ matrix.extras }}]
          py.test
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: |
          make test
